session:
  redisUrl: localhost:6379
  redisDB: 10
db:
  url: postgresql://localhost:5432/golang_example_development?sslmode=disable
  maxOpenConns: 5
  maxIdleConns: 3
  connMaxLifetime: 15m
  logLevel: debug
grpc:
  services:
    products:
      target: localhost:50051
      maxConn: 10
      initConn: 1
      maxLifeDuration: 5m
      idleTimeout: 1s
  clientParameters:
    time: 5m
    timeout: 10s
    permitWithoutStream: false
oauth:
  redisUrl: localhost:6379
  redisDB: 10
  clientStoreInfo:
    123456:
      id: 123456
      secret: 12345678
      domain: localhost:9094
auth:
  services:
    test-service: 1
  relativePath: keys/local
logger:
  debug: true
graphql:
  introspection: true
graphql_resolver:
  productTimeout: 5
tracing:
  jaeger:
    reporter:
      localAgentHostPort: localhost:6831
    disabled: false
    serviceName: golang-example-app-server
products:
  natsUrl: http://localhost:4222
  subject: products
services:
  oauthClient:
    url: http://localhost:9094
    port: 9094
    authUrl: http://localhost:9096/authorize
    tokenUrl: http://localhost:9096/token
    clientID: 123456
    clientSecret: 12345678
  productService:
    port: 50051
    healthCheckUrl: localhost:50052
    natsUrl: http://localhost:4222
    subject: products
  healthCheckService:
    port: 50052
    randomDisable: true
